services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=techvn_db
            - DB_USERNAME=admin
            - DB_PASSWORD=123456

    mysql:
        image: mysql:8.0
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=techvn_db
        volumes:
            - mysql-data:/var/lib/mysql
volumes:
    mysql-data:
